// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/exams": {
    params: {};
  };
  "/guide/:postSlug": {
    params: {
      "postSlug": string;
    };
  };
  "/exam/:slug": {
    params: {
      "slug": string;
    };
  };
  "/exam/:slug/overview": {
    params: {
      "slug": string;
    };
  };
  "/question/:slug": {
    params: {
      "slug": string;
    };
  };
  "/pyq/:slug": {
    params: {
      "slug": string;
    };
  };
  "/mock-test/:slug": {
    params: {
      "slug": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/analytics/:examSlug": {
    params: {
      "examSlug": string;
    };
  };
  "/mock-attempt/:slug": {
    params: {
      "slug": string;
    };
  };
  "/paper-attempt/:slug": {
    params: {
      "slug": string;
    };
  };
  "/exam": {
    params: {};
  };
  "/pyq-papers": {
    params: {};
  };
  "/pdf-library": {
    params: {};
  };
  "/tests": {
    params: {};
  };
  "/practice": {
    params: {};
  };
  "/attempted": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/privacy" | "/terms" | "/exams" | "/guide/:postSlug" | "/exam/:slug" | "/exam/:slug/overview" | "/question/:slug" | "/pyq/:slug" | "/mock-test/:slug" | "/dashboard" | "/admin" | "/analytics" | "/analytics/:examSlug" | "/mock-attempt/:slug" | "/paper-attempt/:slug" | "/exam" | "/pyq-papers" | "/pdf-library" | "/tests" | "/practice" | "/attempted";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/exams.tsx": {
    id: "routes/exams";
    page: "/exams";
  };
  "routes/guide.$postSlug.tsx": {
    id: "routes/guide.$postSlug";
    page: "/guide/:postSlug";
  };
  "routes/exam.$slug.tsx": {
    id: "routes/exam.$slug";
    page: "/exam/:slug";
  };
  "routes/exam.$slug.overview.tsx": {
    id: "routes/exam.$slug.overview";
    page: "/exam/:slug/overview";
  };
  "routes/question.$slug.tsx": {
    id: "routes/question.$slug";
    page: "/question/:slug";
  };
  "routes/pyq.$slug.tsx": {
    id: "routes/pyq.$slug";
    page: "/pyq/:slug";
  };
  "routes/mock-test.$slug.tsx": {
    id: "routes/mock-test.$slug";
    page: "/mock-test/:slug";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/analytics.$examSlug.tsx": {
    id: "routes/analytics.$examSlug";
    page: "/analytics/:examSlug";
  };
  "routes/mock-attempt.$slug.tsx": {
    id: "routes/mock-attempt.$slug";
    page: "/mock-attempt/:slug";
  };
  "routes/paper-attempt.$slug.tsx": {
    id: "routes/paper-attempt.$slug";
    page: "/paper-attempt/:slug";
  };
  "routes/redirect-exams.tsx": {
    id: "redir-exam";
    page: "/exam";
  } | {
    id: "redir-pyq-papers";
    page: "/pyq-papers";
  } | {
    id: "redir-pdf-library";
    page: "/pdf-library";
  } | {
    id: "redir-tests";
    page: "/tests";
  } | {
    id: "redir-practice";
    page: "/practice";
  };
  "routes/redirect-analytics.tsx": {
    id: "redir-attempted";
    page: "/attempted";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/exams": typeof import("./app/routes/exams.tsx");
  "routes/guide.$postSlug": typeof import("./app/routes/guide.$postSlug.tsx");
  "routes/exam.$slug": typeof import("./app/routes/exam.$slug.tsx");
  "routes/exam.$slug.overview": typeof import("./app/routes/exam.$slug.overview.tsx");
  "routes/question.$slug": typeof import("./app/routes/question.$slug.tsx");
  "routes/pyq.$slug": typeof import("./app/routes/pyq.$slug.tsx");
  "routes/mock-test.$slug": typeof import("./app/routes/mock-test.$slug.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
  "routes/analytics.$examSlug": typeof import("./app/routes/analytics.$examSlug.tsx");
  "routes/mock-attempt.$slug": typeof import("./app/routes/mock-attempt.$slug.tsx");
  "routes/paper-attempt.$slug": typeof import("./app/routes/paper-attempt.$slug.tsx");
  "redir-exam": typeof import("./app/routes/redirect-exams.tsx");
  "redir-pyq-papers": typeof import("./app/routes/redirect-exams.tsx");
  "redir-pdf-library": typeof import("./app/routes/redirect-exams.tsx");
  "redir-tests": typeof import("./app/routes/redirect-exams.tsx");
  "redir-practice": typeof import("./app/routes/redirect-exams.tsx");
  "redir-attempted": typeof import("./app/routes/redirect-analytics.tsx");
};